---
- name: Run juniper commands
  hosts: juniper
  connection: local
  gather_facts: false

  tasks:

    - name: get base information
      junos_command:
        commands:
          - show chassis hardware
          - show system uptime
        display: text
      register: output

    - debug: var=output.stdout_lines  
